[package]
name = "bibtex-parser"
version = "0.1.0"
authors = ["Blazej Sewera <code@sewera.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
