use crate::s;

#[derive(Debug, PartialEq)]
pub(crate) enum EntryProperty {
    Abstract,
    Afterword,
    Annotation,
    Author,
    AuthorType,
    BookAuthor,
    BookPagination,
    BookSubtitle,
    Chapter,
    Commentator,
    Date,
    Doi,
    Edition,
    EditorType,
    Eid,
    EntrySubtype,
    EPrint,
    EPrintType,
    EPrintClass,
    EventDate,
    EventTitle,
    File,
    Foreword,
    Holder,
    HowPublished,
    IndexTitle,
    Institution,
    Introduction,
    Isan,
    Isbn,
    Ismn,
    Isrn,
    Issue,
    IssueSubtitle,
    IssueTitle,
    Iswc,
    JournalSubtitle,
    JournalTitle,
    Label,
    Language,
    Library,
    Location,
    MainSubtitle,
    MainTitle,
    Month,
    Note,
    Number,
    Organization,
    OrigDate,
    OrigLanguage,
    OrigLocation,
    OrigPublisher,
    OrigTitle,
    Pages,
    PageTotal,
    Pagination,
    Part,
    Publisher,
    PubState,
    ReprintTitle,
    Series,
    ShortAuthor,
    ShortEdition,
    Shorthand,
    ShorthandIntro,
    ShortJournal,
    ShortSeries,
    ShortTitle,
    Subtitle,
    Title,
    Translator,
    Type,
    Url,
    Venue,
    Version,
    Volume,
    Year,
    Invalid(String),
}

impl EntryProperty {
    pub(crate) fn from_str(s: &str) -> EntryProperty {
        match s {
            "abstract" => EntryProperty::Abstract,
            "afterword" => EntryProperty::Afterword,
            "annotation" => EntryProperty::Annotation,
            "annotator" => EntryProperty::Annotation,
            "author" => EntryProperty::Author,
            "authortype" => EntryProperty::AuthorType,
            "bookauthor" => EntryProperty::BookAuthor,
            "bookpagination" => EntryProperty::BookPagination,
            "booksubtitle" => EntryProperty::BookSubtitle,
            "booktitle" => EntryProperty::BookSubtitle,
            "chapter" => EntryProperty::Chapter,
            "commentator" => EntryProperty::Commentator,
            "date" => EntryProperty::Date,
            "doi" => EntryProperty::Doi,
            "edition" => EntryProperty::Edition,
            "editor" => EntryProperty::Edition,
            "editortype" => EntryProperty::EditorType,
            "eid" => EntryProperty::Eid,
            "entrysubtype" => EntryProperty::EntrySubtype,
            "eprint" => EntryProperty::EPrint,
            "eprinttype" => EntryProperty::EPrintType,
            "eprintclass" => EntryProperty::EPrintClass,
            "eventdate" => EntryProperty::EventDate,
            "eventtitle" => EntryProperty::EventTitle,
            "file" => EntryProperty::File,
            "foreword" => EntryProperty::Foreword,
            "holder" => EntryProperty::Holder,
            "howpublished" => EntryProperty::HowPublished,
            "indextitle" => EntryProperty::IndexTitle,
            "institution" => EntryProperty::Institution,
            "introduction" => EntryProperty::Introduction,
            "isan" => EntryProperty::Isan,
            "isbn" => EntryProperty::Isbn,
            "ismn" => EntryProperty::Ismn,
            "isrn" => EntryProperty::Isrn,
            "issue" => EntryProperty::Issue,
            "issuesubtitle" => EntryProperty::IssueSubtitle,
            "issuetitle" => EntryProperty::IssueTitle,
            "iswc" => EntryProperty::Iswc,
            "journalsubtitle" => EntryProperty::JournalSubtitle,
            "journaltitle" => EntryProperty::JournalTitle,
            "label" => EntryProperty::Label,
            "language" => EntryProperty::Language,
            "library" => EntryProperty::Library,
            "location" => EntryProperty::Location,
            "mainsubtitle" => EntryProperty::MainSubtitle,
            "maintitle" => EntryProperty::MainTitle,
            "month" => EntryProperty::Month,
            "note" => EntryProperty::Note,
            "number" => EntryProperty::Number,
            "organization" => EntryProperty::Organization,
            "origdate" => EntryProperty::OrigDate,
            "origlanguage" => EntryProperty::OrigLanguage,
            "origlocation" => EntryProperty::OrigLocation,
            "origpublisher" => EntryProperty::OrigPublisher,
            "origtitle" => EntryProperty::OrigTitle,
            "pages" => EntryProperty::Pages,
            "pagetotal" => EntryProperty::PageTotal,
            "pagination" => EntryProperty::Pagination,
            "part" => EntryProperty::Part,
            "publisher" => EntryProperty::Publisher,
            "pubstate" => EntryProperty::PubState,
            "reprinttitle" => EntryProperty::ReprintTitle,
            "series" => EntryProperty::Series,
            "shortauthor" => EntryProperty::ShortAuthor,
            "shortedition" => EntryProperty::ShortEdition,
            "shorthand" => EntryProperty::Shorthand,
            "shorthandintro" => EntryProperty::ShorthandIntro,
            "shortjournal" => EntryProperty::ShortJournal,
            "shortseries" => EntryProperty::ShortSeries,
            "shorttitle" => EntryProperty::ShortTitle,
            "subtitle" => EntryProperty::Subtitle,
            "title" => EntryProperty::Title,
            "translator" => EntryProperty::Translator,
            "type" => EntryProperty::Type,
            "url" => EntryProperty::Url,
            "venue" => EntryProperty::Venue,
            "version" => EntryProperty::Version,
            "volume" => EntryProperty::Volume,
            "year" => EntryProperty::Year,
            invalid_property => EntryProperty::Invalid(s!(invalid_property)),
        }
    }
}
